// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HotkeysController from "./hotkeys_controller"
application.register("hotkeys", HotkeysController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)
