// This file is auto-generated by ./bin/rails view_component:stimulus_manifest:update
// Run that command whenever you add a new controller in ViewComponent

import { application } from "../javascript/controllers/application"

import DialogComponentController from "./dialog_component_controller"
application.register("dialog-component", DialogComponentController)
